### PR TITLE
Fixed travis tests 

### PR DESCRIPTION
**Pull request by TomCaserta**
This should fix the travis tests that appear to be failing. (Checking if its actually going to work as I cant easilly test this. Just assuming this is the reason why it is failing. If its not I'll close this PR and someone else can fix!)

### CODE REVIEW

**Comment by TomCaserta** [comment]
Hmm the test should have actually failed by the looks of it.

Looked at the previous build and it seemed like the v8js extension was being put in the php.ini automatically before... I wonder what changed.

**Comment by talyssonoc** [comment]
PECL technically adds v8js to php.ini, but now the test pass... that's weird. Maybe some instability on Travis? Gonna try rerun the builds and see if they pass now. If they don't, maybe Travis changed some internal behavior when using PECL and I can approve your PR.

Thanks!

**Comment by TomCaserta** [comment]
Yeah, it cant find the php ini if you look at the travis logs so it didnt add it so I assumed something changed. In any case this works although it doesnt actually check the output of the tests (and appears it never has) travis is just accepting that it ran rather than if there was errors in the tests.

The repository is currently in a state of not working at all by the way since the upgrade to react .14.

**Comment by talyssonoc** [comment]
I've been kind of busy and my computer is with some problems, I'm unable to fix it right now. Gonna try to fix it when I can, but PRs that try to fix the problems are totally welcome!

**Comment by TomCaserta** [comment]
Fair enough, thats fine, I'll fork and get it working later tonight and create PR.

**Comment by talyssonoc** [comment]
Thanks!

**Comment by TomCaserta** [comment]
No longer required

**Pull request closed without merging**
